//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website_Course_AVG.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Website_Course_AVG.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to account.
        /// </summary>
        public static string account {
            get {
                return ResourceManager.GetString("account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to account..
        /// </summary>
        public static string account_ {
            get {
                return ResourceManager.GetString("account.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Comment Successful!.
        /// </summary>
        public static string Add_Comment_Successful_ {
            get {
                return ResourceManager.GetString("Add Comment Successful!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Note.
        /// </summary>
        public static string Add_Note {
            get {
                return ResourceManager.GetString("Add Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Note At.
        /// </summary>
        public static string Add_Note_At {
            get {
                return ResourceManager.GetString("Add Note At", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Note Successful.
        /// </summary>
        public static string Add_Note_Successful {
            get {
                return ResourceManager.GetString("Add Note Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Cart.
        /// </summary>
        public static string Add_to_Cart {
            get {
                return ResourceManager.GetString("Add to Cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After 30 minutes you will be able to comment again.
        /// </summary>
        public static string After_30_minutes_you_will_be_able_to_comment_again {
            get {
                return ResourceManager.GetString("After 30 minutes you will be able to comment again", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        public static string Approve {
            get {
                return ResourceManager.GetString("Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to download the exercise?.
        /// </summary>
        public static string Are_you_sure_you_want_to_download_the_exercise_ {
            get {
                return ResourceManager.GetString("Are you sure you want to download the exercise?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associate your.
        /// </summary>
        public static string Associate_your {
            get {
                return ResourceManager.GetString("Associate your", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Association Form.
        /// </summary>
        public static string Association_Form {
            get {
                return ResourceManager.GetString("Association Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AVG Courses - Reset Password.
        /// </summary>
        public static string AVG_Courses___Reset_Password {
            get {
                return ResourceManager.GetString("AVG Courses - Reset Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic.
        /// </summary>
        public static string Basic {
            get {
                return ResourceManager.GetString("Basic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to be sent again.
        /// </summary>
        public static string be_sent_again {
            get {
                return ResourceManager.GetString("be sent again", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog.
        /// </summary>
        public static string Blog {
            get {
                return ResourceManager.GetString("Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card details.
        /// </summary>
        public static string Card_details {
            get {
                return ResourceManager.GetString("Card details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart.
        /// </summary>
        public static string Cart {
            get {
                return ResourceManager.GetString("Cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Language Successful!.
        /// </summary>
        public static string Change_Language_Successful_ {
            get {
                return ResourceManager.GetString("Change Language Successful!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout.
        /// </summary>
        public static string Checkout {
            get {
                return ResourceManager.GetString("Checkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to change password.
        /// </summary>
        public static string Click_here_to_change_password {
            get {
                return ResourceManager.GetString("Click here to change password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Lesson.
        /// </summary>
        public static string Content_Lesson {
            get {
                return ResourceManager.GetString("Content Lesson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost.
        /// </summary>
        public static string Cost {
            get {
                return ResourceManager.GetString("Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course.
        /// </summary>
        public static string Course {
            get {
                return ResourceManager.GetString("Course", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course content.
        /// </summary>
        public static string Course_content {
            get {
                return ResourceManager.GetString("Course content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Account.
        /// </summary>
        public static string Create_Account {
            get {
                return ResourceManager.GetString("Create Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete successful.
        /// </summary>
        public static string Delete_successful {
            get {
                return ResourceManager.GetString("Delete successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete successful!.
        /// </summary>
        public static string Delete_successful_ {
            get {
                return ResourceManager.GetString("Delete successful!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have any questions about this lesson?.
        /// </summary>
        public static string Do_you_have_any_questions_about_this_lesson_ {
            get {
                return ResourceManager.GetString("Do you have any questions about this lesson?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have account?.
        /// </summary>
        public static string Don_t_have_account_ {
            get {
                return ResourceManager.GetString("Don\'t have account?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Exercises.
        /// </summary>
        public static string Download_Exercises {
            get {
                return ResourceManager.GetString("Download Exercises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the following password reset code:.
        /// </summary>
        public static string Enter_the_following_password_reset_code_ {
            get {
                return ResourceManager.GetString("Enter the following password reset code:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Unknown.
        /// </summary>
        public static string Error_Unknown {
            get {
                return ResourceManager.GetString("Error Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Unknown, Please Try Again!.
        /// </summary>
        public static string Error_Unknown__Please_Try_Again_ {
            get {
                return ResourceManager.GetString("Error Unknown, Please Try Again!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exercise is null.
        /// </summary>
        public static string Exercise_is_null {
            get {
                return ResourceManager.GetString("Exercise is null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Favorite Course.
        /// </summary>
        public static string Find_Favorite_Course {
            get {
                return ResourceManager.GetString("Find Favorite Course", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for details on setting up this ASP.NET application to support logging in via external services..
        /// </summary>
        public static string for_details_on_setting_up_this_ASP_NET_application_to_support_logging_in_via_external_services_ {
            get {
                return ResourceManager.GetString("for details on setting up this ASP.NET application to support logging in via exte" +
                        "rnal services.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for details on setting up this ASP.NET application to support two-factor authentication..
        /// </summary>
        public static string for_details_on_setting_up_this_ASP_NET_application_to_support_two_factor_authentication_ {
            get {
                return ResourceManager.GetString("for details on setting up this ASP.NET application to support two-factor authenti" +
                        "cation.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password?.
        /// </summary>
        public static string Forgot_Password_ {
            get {
                return ResourceManager.GetString("Forgot Password?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free.
        /// </summary>
        public static string Free {
            get {
                return ResourceManager.GetString("Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from basic to advanced. from basic.
        /// </summary>
        public static string from_basic_to_advanced__from_basic {
            get {
                return ResourceManager.GetString("from basic to advanced. from basic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Comment Success.
        /// </summary>
        public static string Get_Comment_Success {
            get {
                return ResourceManager.GetString("Get Comment Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Exercise Successful!.
        /// </summary>
        public static string Get_Exercise_Successful_ {
            get {
                return ResourceManager.GetString("Get Exercise Successful!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Homepage.
        /// </summary>
        public static string Go_to_Homepage {
            get {
                return ResourceManager.GetString("Go to Homepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Error.
        /// </summary>
        public static string Has_Error {
            get {
                return ResourceManager.GetString("Has Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello,Again.
        /// </summary>
        public static string Hello_Again {
            get {
                return ResourceManager.GetString("Hello,Again", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help Center.
        /// </summary>
        public static string Help_Center {
            get {
                return ResourceManager.GetString("Help Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page.
        /// </summary>
        public static string Home_Page {
            get {
                return ResourceManager.GetString("Home Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid information.
        /// </summary>
        public static string invalid_information {
            get {
                return ResourceManager.GetString("invalid information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Request.
        /// </summary>
        public static string Invalid_Request {
            get {
                return ResourceManager.GetString("Invalid Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It seems you have not registered for the course, please try again. If this is an error, please report to the admin before leaving the site, thank you..
        /// </summary>
        public static string It_seems_you_have_not_registered_for_the_course__please_try_again__If_this_is_an_error__please_report_to_the_admin_before_leaving_the_site__thank_you_ {
            get {
                return ResourceManager.GetString("It seems you have not registered for the course, please try again. If this is an " +
                        "error, please report to the admin before leaving the site, thank you.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        public static string Languages {
            get {
                return ResourceManager.GetString("Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn HTML CSS for beginners.
        /// </summary>
        public static string Learn_HTML_CSS_for_beginners {
            get {
                return ResourceManager.GetString("Learn HTML CSS for beginners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lesson.
        /// </summary>
        public static string Lesson {
            get {
                return ResourceManager.GetString("Lesson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lessons.
        /// </summary>
        public static string lessons {
            get {
                return ResourceManager.GetString("lessons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked out..
        /// </summary>
        public static string Locked_out_ {
            get {
                return ResourceManager.GetString("Locked out.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in using your.
        /// </summary>
        public static string Log_in_using_your {
            get {
                return ResourceManager.GetString("Log in using your", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log off.
        /// </summary>
        public static string Log_off {
            get {
                return ResourceManager.GetString("Log off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Successful!.
        /// </summary>
        public static string Login_Successful_ {
            get {
                return ResourceManager.GetString("Login Successful!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login with Gmail Successful!.
        /// </summary>
        public static string Login_with_Gmail_Successful_ {
            get {
                return ResourceManager.GetString("Login with Gmail Successful!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout Successful!.
        /// </summary>
        public static string Logout_Successful_ {
            get {
                return ResourceManager.GetString("Logout Successful!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketing.
        /// </summary>
        public static string Marketing {
            get {
                return ResourceManager.GetString("Marketing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min.
        /// </summary>
        public static string min {
            get {
                return ResourceManager.GetString("min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes total length.
        /// </summary>
        public static string minutes_total_length {
            get {
                return ResourceManager.GetString("minutes total length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to missing information.
        /// </summary>
        public static string missing_information {
            get {
                return ResourceManager.GetString("missing information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Momo payment failed.
        /// </summary>
        public static string Momo_payment_failed {
            get {
                return ResourceManager.GetString("Momo payment failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Courses.
        /// </summary>
        public static string My_Courses {
            get {
                return ResourceManager.GetString("My Courses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Notes.
        /// </summary>
        public static string My_Notes {
            get {
                return ResourceManager.GetString("My Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No course in your cart!.
        /// </summary>
        public static string No_course_in_your_cart_ {
            get {
                return ResourceManager.GetString("No course in your cart!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No courses found, please try again!.
        /// </summary>
        public static string No_courses_found__please_try_again_ {
            get {
                return ResourceManager.GetString("No courses found, please try again!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No courses in your cart.
        /// </summary>
        public static string No_courses_in_your_cart {
            get {
                return ResourceManager.GetString("No courses in your cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not find note.
        /// </summary>
        public static string Not_find_note {
            get {
                return ResourceManager.GetString("Not find note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify.
        /// </summary>
        public static string Notify {
            get {
                return ResourceManager.GetString("Notify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        public static string or {
            get {
                return ResourceManager.GetString("or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or visit.
        /// </summary>
        public static string or_visit {
            get {
                return ResourceManager.GetString("or visit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our website use cookies. By Approve, we assume your permission to deploy cookies as detailed in our Privacy Policy..
        /// </summary>
        public static string Our_website_use_cookies__By_Approve__we_assume_your_permission_to_deploy_cookies_as_detailed_in_our_Privacy_Policy_ {
            get {
                return ResourceManager.GetString("Our website use cookies. By Approve, we assume your permission to deploy cookies " +
                        "as detailed in our Privacy Policy.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our website uses cookies.
        /// </summary>
        public static string Our_website_uses_cookies {
            get {
                return ResourceManager.GetString("Our website uses cookies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        public static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Method.
        /// </summary>
        public static string Payment_Method {
            get {
                return ResourceManager.GetString("Payment Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment success!.
        /// </summary>
        public static string Payment_success_ {
            get {
                return ResourceManager.GetString("Payment success!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your email.
        /// </summary>
        public static string Please_check_your_email {
            get {
                return ResourceManager.GetString("Please check your email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your information and try again later..
        /// </summary>
        public static string Please_check_your_information_and_try_again_later_ {
            get {
                return ResourceManager.GetString("Please check your information and try again later.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please do not comment spam or use vulgar or regionally discriminatory words, Comment once every 30 minutes.
        /// </summary>
        public static string Please_do_not_comment_spam_or_use_vulgar_or_regionally_discriminatory_words__Comment_once_every_30_minutes {
            get {
                return ResourceManager.GetString("Please do not comment spam or use vulgar or regionally discriminatory words, Comm" +
                        "ent once every 30 minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a user name for this site below and click the Register button to finish logging in.
        /// </summary>
        public static string Please_enter_a_user_name_for_this_site_below_and_click_the_Register_button_to_finish_logging_in {
            get {
                return ResourceManager.GetString("Please enter a user name for this site below and click the Register button to fin" +
                        "ish logging in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Practice projects with Figma, hundreds of exercises and challenges, 100% instruction by Son Dang, included flashcards, and more..
        /// </summary>
        public static string Practice_projects_with_Figma__hundreds_of_exercises_and_challenges__100__instruction_by_Son_Dang__included_flashcards__and_more_ {
            get {
                return ResourceManager.GetString("Practice projects with Figma, hundreds of exercises and challenges, 100% instruct" +
                        "ion by Son Dang, included flashcards, and more.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Save Changes.
        /// </summary>
        public static string Press_Save_Changes {
            get {
                return ResourceManager.GetString("Press Save Changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        public static string Privacy {
            get {
                return ResourceManager.GetString("Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pro.
        /// </summary>
        public static string Pro {
            get {
                return ResourceManager.GetString("Pro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceed to Pay.
        /// </summary>
        public static string Proceed_to_Pay {
            get {
                return ResourceManager.GetString("Proceed to Pay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promotion code does not exist..
        /// </summary>
        public static string Promotion_code_does_not_exist_ {
            get {
                return ResourceManager.GetString("Promotion code does not exist.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promotion code has been used up..
        /// </summary>
        public static string Promotion_code_has_been_used_up_ {
            get {
                return ResourceManager.GetString("Promotion code has been used up.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promotion code has expired..
        /// </summary>
        public static string Promotion_code_has_expired_ {
            get {
                return ResourceManager.GetString("Promotion code has expired.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions.
        /// </summary>
        public static string Questions {
            get {
                return ResourceManager.GetString("Questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReactJS course.
        /// </summary>
        public static string ReactJS_course {
            get {
                return ResourceManager.GetString("ReactJS course", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Successful!.
        /// </summary>
        public static string Register_Successful_ {
            get {
                return ResourceManager.GetString("Register Successful!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string Reset_Password {
            get {
                return ResourceManager.GetString("Reset Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password Successful!.
        /// </summary>
        public static string Reset_Password_Successful_ {
            get {
                return ResourceManager.GetString("Reset Password Successful!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes.
        /// </summary>
        public static string Save_changes {
            get {
                return ResourceManager.GetString("Save changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send verification code.
        /// </summary>
        public static string Send_verification_code {
            get {
                return ResourceManager.GetString("Send verification code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent Email Successfully.
        /// </summary>
        public static string Sent_Email_Successfully {
            get {
                return ResourceManager.GetString("Sent Email Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string Sign_In {
            get {
                return ResourceManager.GetString("Sign In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        public static string Sign_out {
            get {
                return ResourceManager.GetString("Sign out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        public static string Sign_up {
            get {
                return ResourceManager.GetString("Sign up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success!.
        /// </summary>
        public static string Success_ {
            get {
                return ResourceManager.GetString("Success!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of Use.
        /// </summary>
        public static string Terms_of_Use {
            get {
                return ResourceManager.GetString("Terms of Use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The course has been purchased.
        /// </summary>
        public static string The_course_has_been_purchased {
            get {
                return ResourceManager.GetString("The course has been purchased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The course is not found, please try again later. If it still doesn&apos;t work, please don&apos;t leave and report to admin so we can handle it, thank you..
        /// </summary>
        public static string The_course_is_not_found__please_try_again_later__If_it_still_doesn_t_work__please_don_t_leave_and_report_to_admin_so_we_can_handle_it__thank_you_ {
            get {
                return ResourceManager.GetString("The course is not found, please try again later. If it still doesn\'t work, please" +
                        " don\'t leave and report to admin so we can handle it, thank you.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The lesson is not found, please try again later. If it still doesn&apos;t work, please don&apos;t leave and report to admin so we can handle it, thank you..
        /// </summary>
        public static string The_lesson_is_not_found__please_try_again_later__If_it_still_doesn_t_work__please_don_t_leave_and_report_to_admin_so_we_can_handle_it__thank_you_ {
            get {
                return ResourceManager.GetString("The lesson is not found, please try again later. If it still doesn\'t work, please" +
                        " don\'t leave and report to admin so we can handle it, thank you.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no external authentication services configured. See.
        /// </summary>
        public static string There_are_no_external_authentication_services_configured__See {
            get {
                return ResourceManager.GetString("There are no external authentication services configured. See", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no two-factor authentication providers configured. See.
        /// </summary>
        public static string There_are_no_two_factor_authentication_providers_configured__See {
            get {
                return ResourceManager.GetString("There are no two-factor authentication providers configured. See", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account has been locked out, please try again later..
        /// </summary>
        public static string This_account_has_been_locked_out__please_try_again_later_ {
            get {
                return ResourceManager.GetString("This account has been locked out, please try again later.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this article.
        /// </summary>
        public static string this_article {
            get {
                return ResourceManager.GetString("this article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two-Factor Authentication:.
        /// </summary>
        public static string Two_Factor_Authentication_ {
            get {
                return ResourceManager.GetString("Two-Factor Authentication:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error, please contact admin to fix the error.
        /// </summary>
        public static string Unknown_error__please_contact_admin_to_fix_the_error {
            get {
                return ResourceManager.GetString("Unknown error, please contact admin to fix the error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error, please contact admin to fix the error , Code Error :.
        /// </summary>
        public static string Unknown_error__please_contact_admin_to_fix_the_error___Code_Error__ {
            get {
                return ResourceManager.GetString("Unknown error, please contact admin to fix the error , Code Error :", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsuccessful login with service..
        /// </summary>
        public static string Unsuccessful_login_with_service_ {
            get {
                return ResourceManager.GetString("Unsuccessful login with service.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Date.
        /// </summary>
        public static string Update_Date {
            get {
                return ResourceManager.GetString("Update Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username and password are wrong !!!.
        /// </summary>
        public static string Username_and_password_are_wrong____ {
            get {
                return ResourceManager.GetString("Username and password are wrong !!!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch Course.
        /// </summary>
        public static string Watch_Course {
            get {
                return ResourceManager.GetString("Watch Course", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are happy to have you back..
        /// </summary>
        public static string We_are_happy_to_have_you_back_ {
            get {
                return ResourceManager.GetString("We are happy to have you back.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have received a password reset request on our website..
        /// </summary>
        public static string We_have_received_a_password_reset_request_on_our_website_ {
            get {
                return ResourceManager.GetString("We have received a password reset request on our website.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We noticed that you pressed forgot password too many times in one day, please try again after 30 minutes, thank you.
        /// </summary>
        public static string We_noticed_that_you_pressed_forgot_password_too_many_times_in_one_day__please_try_again_after_30_minutes__thank_you {
            get {
                return ResourceManager.GetString("We noticed that you pressed forgot password too many times in one day, please try" +
                        " again after 30 minutes, thank you", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What will you learn?.
        /// </summary>
        public static string What_will_you_learn_ {
            get {
                return ResourceManager.GetString("What will you learn?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are logging in !!!.
        /// </summary>
        public static string You_are_logging_in____ {
            get {
                return ResourceManager.GetString("You are logging in !!!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are using too many words that violate community rules.
        /// </summary>
        public static string You_are_using_too_many_words_that_violate_community_rules {
            get {
                return ResourceManager.GetString("You are using too many words that violate community rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to enter here!!!.
        /// </summary>
        public static string You_do_not_have_permission_to_enter_here___ {
            get {
                return ResourceManager.GetString("You do not have permission to enter here!!!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You enter error Code or Re-password.
        /// </summary>
        public static string You_enter_error_Code_or_Re_password {
            get {
                return ResourceManager.GetString("You enter error Code or Re-password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not finished studying the previous lesson, please return to the previous lesson.
        /// </summary>
        public static string You_have_not_finished_studying_the_previous_lesson__please_return_to_the_previous_lesson {
            get {
                return ResourceManager.GetString("You have not finished studying the previous lesson, please return to the previous" +
                        " lesson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve successfully authenticated with.
        /// </summary>
        public static string You_ve_successfully_authenticated_with {
            get {
                return ResourceManager.GetString("You\'ve successfully authenticated with", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your application description page..
        /// </summary>
        public static string Your_application_description_page_ {
            get {
                return ResourceManager.GetString("Your application description page.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your contact page..
        /// </summary>
        public static string Your_contact_page_ {
            get {
                return ResourceManager.GetString("Your contact page.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been reset. Please.
        /// </summary>
        public static string Your_password_has_been_reset__Please {
            get {
                return ResourceManager.GetString("Your password has been reset. Please", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password recovery code is.
        /// </summary>
        public static string Your_password_recovery_code_is {
            get {
                return ResourceManager.GetString("Your password recovery code is", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your request could not be processed due to.
        /// </summary>
        public static string Your_request_could_not_be_processed_due_to {
            get {
                return ResourceManager.GetString("Your request could not be processed due to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your time remain is.
        /// </summary>
        public static string Your_time_remain_is {
            get {
                return ResourceManager.GetString("Your time remain is", resourceCulture);
            }
        }
    }
}
