//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website_Course_AVG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detail_order
    {
        public int id { get; set; }
        public Nullable<long> price { get; set; }
        public Nullable<int> order_id { get; set; }
        public Nullable<int> course_id { get; set; }
    
        public virtual cours cours { get; set; }
        public virtual order order { get; set; }
    }
}
