//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website_Course_AVG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class exercis
    {
        public int id { get; set; }
        public string title { get; set; }
        public string content { get; set; }
        public string source_excercise { get; set; }
        public Nullable<int> lesson_id { get; set; }
    
        public virtual lesson lesson { get; set; }
    }
}
