//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website_Course_AVG.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AVG_Website_CourseEntities : DbContext
    {
        public AVG_Website_CourseEntities()
            : base("name=AVG_Website_CourseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<account> accounts { get; set; }
        public virtual DbSet<blog> blogs { get; set; }
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<comment> comments { get; set; }
        public virtual DbSet<contact> contacts { get; set; }
        public virtual DbSet<cours> courses { get; set; }
        public virtual DbSet<detail_course> detail_course { get; set; }
        public virtual DbSet<detail_order> detail_order { get; set; }
        public virtual DbSet<exercis> exercises { get; set; }
        public virtual DbSet<lesson> lessons { get; set; }
        public virtual DbSet<note> notes { get; set; }
        public virtual DbSet<notification> notifications { get; set; }
        public virtual DbSet<option> options { get; set; }
        public virtual DbSet<order> orders { get; set; }
        public virtual DbSet<promotion> promotions { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
