//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website_Course_AVG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public order()
        {
            this.detail_order = new HashSet<detail_order>();
        }
    
        public int id { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<long> total { get; set; }
        public string type_payment { get; set; }
        public string code_order { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> promotion_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detail_order> detail_order { get; set; }
        public virtual promotion promotion { get; set; }
        public virtual user user { get; set; }
    }
}
